package com.smartTriage.smartTriage_server.module.alert.entity;

import com.smartTriage.smartTriage_server.common.entity.BaseEntity;
import com.smartTriage.smartTriage_server.common.enums.AlertSeverity;
import com.smartTriage.smartTriage_server.common.enums.AlertType;
import com.smartTriage.smartTriage_server.common.enums.EdZone;
import com.smartTriage.smartTriage_server.module.user.entity.User;
import com.smartTriage.smartTriage_server.module.visit.entity.Visit;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * ClinicalAlert — system-generated alert for clinical deterioration or protocol
 * events.
 *
 * Alerts are triggered by:
 * - TEWS escalation
 * - Abnormal vital signs
 * - Waiting time exceeded
 * - Reassessment due
 * - Deterioration pattern detection
 *
 * In a life-critical system, alert latency and reliability are paramount.
 */
@Entity
@Table(name = "clinical_alerts", indexes = {
        @Index(name = "idx_alert_visit", columnList = "visit_id"),
        @Index(name = "idx_alert_type", columnList = "alert_type"),
        @Index(name = "idx_alert_severity", columnList = "severity"),
        @Index(name = "idx_alert_acknowledged", columnList = "is_acknowledged"),
        @Index(name = "idx_alert_created", columnList = "created_at"),
        @Index(name = "idx_alert_active", columnList = "is_active")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ClinicalAlert extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visit_id", nullable = false)
    private Visit visit;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_type", nullable = false, length = 30)
    private AlertType alertType;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false, length = 15)
    private AlertSeverity severity;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    @Column(name = "is_acknowledged", nullable = false)
    @Builder.Default
    private boolean isAcknowledged = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acknowledged_by_id")
    private User acknowledgedBy;

    @Column(name = "acknowledged_at")
    private Instant acknowledgedAt;

    /**
     * B5 — free-text note the clinician entered when acknowledging (or
     * dismissing) the alert. The dialog captured this but it was previously
     * dropped (no API body, no column). Nullable.
     */
    @Column(name = "acknowledgment_note", length = 1000)
    private String acknowledgmentNote;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private boolean autoGenerated = true;

    // ====================================================================
    // ZONE-AWARE ESCALATION FIELDS
    // ====================================================================

    /** Target ED zone for this alert (derived from triage category) */
    @Enumerated(EnumType.STRING)
    @Column(name = "target_zone", length = 20)
    private EdZone targetZone;

    /**
     * Current escalation tier: 1 = zone doctor, 2 = all doctors, 3 = everyone +
     * alarm
     */
    @Column(name = "escalation_tier", nullable = false)
    @Builder.Default
    private int escalationTier = 1;

    /** Timestamp of the last escalation */
    @Column(name = "escalated_at")
    private Instant escalatedAt;

    /** Doctor specifically targeted by the alert (zone doctor for Tier 1) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "target_doctor_id")
    private User targetDoctor;

    /** SATS maximum wait time in minutes for the triage category */
    @Column(name = "sats_target_minutes")
    private Integer satsTargetMinutes;

    // ====================================================================
    // ROUND 4a — RETRIAGE_REQUIRED trigger audit
    // ====================================================================

    /**
     * For RETRIAGE_REQUIRED alerts: the clinical-sign event that produced
     * the alert. Populated by both the AutoBump and Suggest paths in
     * TriageService. Null for every other alert type.
     */
    @Column(name = "triggering_sign_event_id")
    private UUID triggeringSignEventId;

    /**
     * Denormalised sign code matching the trigger event (e.g.
     * "MSAT_VU_CHEST_PAIN"). Stored alongside the FK so the frontend's
     * alert click-handler has the code on the alert object directly,
     * without a follow-up fetch on every alert render.
     */
    @Column(name = "triggering_sign_code", length = 60)
    private String triggeringSignCode;
}
