package com.smartTriage.smartTriage_server.common.report;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.ColumnText;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * PdfReport — the SmartTriage branded report kit. ONE house style for every
 * exportable PDF (PCR, handover/SBAR, MOH, lab pack, safety incident) so they
 * all read as a polished, consistent, professional deliverable rather than a
 * bare printout.
 *
 * <p>What it standardises:
 * <ul>
 *   <li><b>Brand masthead</b> — the SmartTriage logo + wordmark + the report
 *       title, the owning organisation (hospital), and an attribution line
 *       ("Generated by X · when") on page 1.</li>
 *   <li><b>Palette + typography</b> — a single cyan/slate scheme and Helvetica
 *       type scale (title / section / label / body).</li>
 *   <li><b>Content helpers</b> — section headers (accent bar + hairline),
 *       clean two-column key/value tables, vitals stat-tiles, bullet lists, a
 *       narrative panel, and alert banners — readable at a glance, not a data
 *       dump.</li>
 *   <li><b>Every-page chrome</b> — a slim running header on pages ≥ 2 and a
 *       footer carrying the confidentiality label, the attribution (who
 *       exported + when — so the artifact is traceable), and "Page X of Y".</li>
 * </ul>
 *
 * <p>Usage:
 * <pre>
 *   PdfReport r = PdfReport.begin(new Spec("PRE-HOSPITAL PATIENT CARE REPORT (PCR)",
 *           "Patient Care Report", hospitalName, orgMetaLines, exportedByName,
 *           "EMS patient care report"));
 *   r.sectionHeader("Run &amp; Crew");
 *   r.keyValues(List.of(kv("Service", "BLS"), kv("Unit", "A-12")));
 *   byte[] pdf = r.finish();
 * </pre>
 * OpenPDF (com.lowagie). Must run inside the caller's load transaction if it
 * reads lazy associations.
 */
public final class PdfReport {

    // ── Brand palette (mirrors the FE cyan/slate design tokens) ──
    public static final Color BRAND = new Color(8, 145, 178);        // cyan-600 — primary
    public static final Color BRAND_DEEP = new Color(3, 105, 161);   // sky-700 — headings
    public static final Color INK = new Color(15, 23, 42);           // slate-900 — body
    public static final Color MUTED = new Color(100, 116, 139);      // slate-500 — labels/meta
    public static final Color HAIRLINE = new Color(203, 213, 225);   // slate-300 — rules/borders
    public static final Color PANEL = new Color(248, 250, 252);      // slate-50 — panels/tiles
    public static final Color BAND = new Color(236, 254, 255);       // cyan-50 — masthead wash
    public static final Color ACCENT = new Color(217, 119, 6);       // amber-600 — highlights
    public static final Color DANGER = new Color(190, 30, 45);       // red — alerts

    // ── Type scale (Helvetica) ──
    public static final Font F_WORDMARK = new Font(Font.HELVETICA, 17, Font.BOLD, BRAND_DEEP);
    public static final Font F_TAGLINE  = new Font(Font.HELVETICA, 7, Font.NORMAL, MUTED);
    public static final Font F_TITLE    = new Font(Font.HELVETICA, 14, Font.BOLD, INK);
    public static final Font F_ORG      = new Font(Font.HELVETICA, 10, Font.BOLD, BRAND_DEEP);
    public static final Font F_META     = new Font(Font.HELVETICA, 8, Font.NORMAL, MUTED);
    public static final Font F_SECTION  = new Font(Font.HELVETICA, 11, Font.BOLD, BRAND_DEEP);
    public static final Font F_LABEL    = new Font(Font.HELVETICA, 8, Font.BOLD, MUTED);
    public static final Font F_VALUE    = new Font(Font.HELVETICA, 9, Font.NORMAL, INK);
    public static final Font F_VALUE_BD = new Font(Font.HELVETICA, 9, Font.BOLD, INK);
    public static final Font F_BODY     = new Font(Font.HELVETICA, 9, Font.NORMAL, INK);
    public static final Font F_TILE_NUM = new Font(Font.HELVETICA, 12, Font.BOLD, INK);
    public static final Font F_TILE_LBL = new Font(Font.HELVETICA, 6.5f, Font.BOLD, MUTED);
    public static final Font F_ALERT    = new Font(Font.HELVETICA, 10, Font.BOLD, DANGER);

    private static final DateTimeFormatter TS =
            DateTimeFormatter.ofPattern("dd MMM yyyy · HH:mm").withZone(ZoneId.of("Africa/Kigali"));

    // Cache the logo BYTES (not an Image): an OpenPDF Image carries per-document
    // state, so a shared instance would corrupt concurrent renders. We build a
    // fresh Image per report from these cached bytes. EMPTY = classpath miss.
    private static volatile byte[] cachedLogoBytes;
    private static final byte[] EMPTY = new byte[0];

    /** Report metadata driving the masthead + footer chrome. */
    public record Spec(
            String reportTitle,          // e.g. "PRE-HOSPITAL PATIENT CARE REPORT (PCR)"
            String reportKind,           // short footer label, e.g. "Patient Care Report"
            String orgName,              // owning hospital / organisation
            List<String> orgMeta,        // address / code / phone lines (may be empty)
            String exportedByName,       // who generated the export (attribution)
            String confidentiality       // footer confidentiality clause
    ) {}

    /** A label/value pair for key-value tables and stat tiles. */
    public record KeyVal(String label, String value) {}

    public static KeyVal kv(String label, String value) { return new KeyVal(label, value); }

    private final Document doc;
    private final ByteArrayOutputStream out;

    private PdfReport(Document doc, ByteArrayOutputStream out) {
        this.doc = doc;
        this.out = out;
    }

    /** Open a branded A4 report and lay down the masthead. */
    public static PdfReport begin(Spec spec) {
        Document doc = new Document(PageSize.A4, 42, 42, 44, 56);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            // ONE generation instant for the whole document — reused by the masthead AND the
            // every-page footer so a multi-page report never shows drifting timestamps.
            Instant generatedAt = Instant.now();
            PdfWriter writer = PdfWriter.getInstance(doc, out);
            writer.setPageEvent(new Chrome(spec, generatedAt));
            doc.open();
            PdfReport r = new PdfReport(doc, out);
            r.masthead(spec, generatedAt);
            return r;
        } catch (Exception e) {
            throw new IllegalStateException("Could not start PDF report", e);
        }
    }

    // ── Masthead (page 1) ────────────────────────────────────────────
    private void masthead(Spec spec, Instant generatedAt) throws Exception {
        PdfPTable head = new PdfPTable(new float[]{62, 38});
        head.setWidthPercentage(100);
        head.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        // Left: logo + wordmark + tagline.
        PdfPTable left = new PdfPTable(new float[]{18, 82});
        left.getDefaultCell().setBorder(Rectangle.NO_BORDER);
        left.getDefaultCell().setVerticalAlignment(Element.ALIGN_MIDDLE);
        Image logo = logo();
        PdfPCell logoCell = new PdfPCell();
        logoCell.setBorder(Rectangle.NO_BORDER);
        logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        if (logo != null) {
            logo.scaleToFit(34, 34);
            logoCell.addElement(logo);
        }
        left.addCell(logoCell);
        PdfPCell mark = new PdfPCell();
        mark.setBorder(Rectangle.NO_BORDER);
        mark.setVerticalAlignment(Element.ALIGN_MIDDLE);
        Paragraph wm = new Paragraph("SmartTriage", F_WORDMARK);
        wm.setLeading(15f);
        mark.addElement(wm);
        mark.addElement(new Paragraph("Emergency care, coordinated.", F_TAGLINE));
        left.addCell(mark);
        PdfPCell leftWrap = new PdfPCell(left);
        leftWrap.setBorder(Rectangle.NO_BORDER);
        leftWrap.setVerticalAlignment(Element.ALIGN_MIDDLE);
        head.addCell(leftWrap);

        // Right: report title + org + attribution, right-aligned.
        PdfPCell right = new PdfPCell();
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        Paragraph t = new Paragraph(spec.reportTitle(), F_TITLE);
        t.setAlignment(Element.ALIGN_RIGHT);
        t.setLeading(15f);
        right.addElement(t);
        if (spec.orgName() != null && !spec.orgName().isBlank()) {
            Paragraph o = new Paragraph(spec.orgName(), F_ORG);
            o.setAlignment(Element.ALIGN_RIGHT);
            right.addElement(o);
        }
        if (spec.orgMeta() != null) {
            for (String line : spec.orgMeta()) {
                if (line != null && !line.isBlank()) {
                    Paragraph m = new Paragraph(line, F_META);
                    m.setAlignment(Element.ALIGN_RIGHT);
                    right.addElement(m);
                }
            }
        }
        head.addCell(right);
        doc.add(head);

        // Attribution line + accent rule.
        String who = (spec.exportedByName() != null && !spec.exportedByName().isBlank())
                ? spec.exportedByName() : "SmartTriage user";
        Paragraph attr = new Paragraph("Generated by " + who + " · " + TS.format(generatedAt), F_META);
        attr.setSpacingBefore(6f);
        doc.add(attr);
        doc.add(accentRule(2.0f, BRAND));
        spacer(4f);
    }

    // ── Content helpers ──────────────────────────────────────────────

    /** Section heading — brand accent bar + label + hairline underline. */
    public void sectionHeader(String label) {
        try {
            PdfPTable t = new PdfPTable(new float[]{1.5f, 98.5f});
            t.setWidthPercentage(100);
            t.setSpacingBefore(11f);
            t.setSpacingAfter(2f);
            PdfPCell bar = new PdfPCell();
            bar.setBorder(Rectangle.NO_BORDER);
            bar.setBackgroundColor(BRAND);
            bar.setFixedHeight(13f);
            t.addCell(bar);
            PdfPCell lbl = new PdfPCell(new Phrase(" " + label.toUpperCase(), F_SECTION));
            lbl.setBorder(Rectangle.BOTTOM);
            lbl.setBorderColor(HAIRLINE);
            lbl.setBorderWidthBottom(0.8f);
            lbl.setPaddingBottom(3f);
            lbl.setVerticalAlignment(Element.ALIGN_BOTTOM);
            t.addCell(lbl);
            doc.add(t);
        } catch (Exception e) {
            throw new IllegalStateException("PDF sectionHeader failed", e);
        }
    }

    /** Two-column key/value table. Blank values are dropped so it never shows "—" noise. */
    public void keyValues(List<KeyVal> pairs) {
        List<KeyVal> shown = pairs.stream()
                .filter(p -> p.value() != null && !p.value().isBlank())
                .toList();
        if (shown.isEmpty()) return;
        try {
            PdfPTable t = new PdfPTable(new float[]{30, 70});
            t.setWidthPercentage(100);
            t.setSpacingBefore(3f);
            for (KeyVal p : shown) {
                t.addCell(kvCell(p.label(), F_LABEL, Element.ALIGN_LEFT));
                t.addCell(kvCell(p.value(), F_VALUE, Element.ALIGN_LEFT));
            }
            doc.add(t);
        } catch (Exception e) {
            throw new IllegalStateException("PDF keyValues failed", e);
        }
    }

    private static PdfPCell kvCell(String text, Font font, int align) {
        PdfPCell c = new PdfPCell(new Phrase(text, font));
        c.setBorder(Rectangle.BOTTOM);
        c.setBorderColor(new Color(226, 232, 240)); // slate-200 — very light row rule
        c.setBorderWidthBottom(0.4f);
        c.setHorizontalAlignment(align);
        c.setPadding(4f);
        c.setPaddingLeft(6f);
        return c;
    }

    /**
     * A row of bordered stat tiles (label + big value) — for vitals / headline
     * numbers. Reads at a glance far better than a key:value list. Empty values
     * are skipped; renders nothing if all empty.
     */
    public void statTiles(List<KeyVal> tiles) {
        List<KeyVal> shown = tiles.stream()
                .filter(p -> p.value() != null && !p.value().isBlank())
                .toList();
        if (shown.isEmpty()) return;
        try {
            int cols = Math.min(shown.size(), 6);
            PdfPTable t = new PdfPTable(cols);
            t.setWidthPercentage(100);
            t.setSpacingBefore(4f);
            t.getDefaultCell().setBorder(Rectangle.NO_BORDER);
            for (int i = 0; i < shown.size(); i++) {
                KeyVal k = shown.get(i);
                PdfPCell cell = new PdfPCell();
                cell.setBorder(Rectangle.BOX);
                cell.setBorderColor(HAIRLINE);
                cell.setBackgroundColor(PANEL);
                cell.setPadding(6f);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                Paragraph num = new Paragraph(k.value(), F_TILE_NUM);
                num.setAlignment(Element.ALIGN_CENTER);
                cell.addElement(num);
                Paragraph lbl = new Paragraph(k.label().toUpperCase(), F_TILE_LBL);
                lbl.setAlignment(Element.ALIGN_CENTER);
                cell.addElement(lbl);
                t.addCell(cell);
            }
            // Pad the final row so tiles keep a uniform width.
            int rem = shown.size() % cols;
            if (rem != 0) for (int i = rem; i < cols; i++) {
                PdfPCell blank = new PdfPCell();
                blank.setBorder(Rectangle.NO_BORDER);
                t.addCell(blank);
            }
            doc.add(t);
        } catch (Exception e) {
            throw new IllegalStateException("PDF statTiles failed", e);
        }
    }

    /** Bulleted list (e.g. interventions, medications). */
    public void bullets(List<String> items) {
        if (items == null) return;
        try {
            for (String item : items) {
                if (item == null || item.isBlank()) continue;
                Paragraph p = new Paragraph();
                p.add(new Phrase("•  ", new Font(Font.HELVETICA, 9, Font.BOLD, BRAND)));
                p.add(new Phrase(item, F_BODY));
                p.setLeading(12f);
                p.setSpacingAfter(1.5f);
                p.setIndentationLeft(4f);
                doc.add(p);
            }
        } catch (Exception e) {
            throw new IllegalStateException("PDF bullets failed", e);
        }
    }

    /** Free-text narrative in a subtle panel — readable prose, not a code block. */
    public void narrative(String text) {
        if (text == null || text.isBlank()) return;
        try {
            PdfPCell cell = new PdfPCell();
            cell.setBackgroundColor(PANEL);
            cell.setBorder(Rectangle.BOX);
            cell.setBorderColor(HAIRLINE);
            cell.setPadding(8f);
            for (String para : text.split("\n", -1)) {
                Paragraph p = new Paragraph(para.isBlank() ? " " : para, F_BODY);
                p.setLeading(12.5f);
                cell.addElement(p);
            }
            PdfPTable wrap = new PdfPTable(1);
            wrap.setWidthPercentage(100);
            wrap.setSpacingBefore(3f);
            wrap.addCell(cell);
            doc.add(wrap);
        } catch (Exception e) {
            throw new IllegalStateException("PDF narrative failed", e);
        }
    }

    /** A prominent alert banner (e.g. unidentified patient, critical flag). */
    public void alertBanner(String text) {
        if (text == null || text.isBlank()) return;
        try {
            PdfPCell cell = new PdfPCell(new Phrase(text, F_ALERT));
            cell.setBackgroundColor(new Color(254, 242, 242)); // red-50
            cell.setBorder(Rectangle.BOX);
            cell.setBorderColor(DANGER);
            cell.setBorderWidth(0.8f);
            cell.setPadding(7f);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPTable wrap = new PdfPTable(1);
            wrap.setWidthPercentage(100);
            wrap.setSpacingBefore(4f);
            wrap.setSpacingAfter(2f);
            wrap.addCell(cell);
            doc.add(wrap);
        } catch (Exception e) {
            throw new IllegalStateException("PDF alertBanner failed", e);
        }
    }

    /** A bold patient/subject name line under the masthead. */
    public void subjectHeadline(String name, String metaLine) {
        try {
            Paragraph n = new Paragraph(name, new Font(Font.HELVETICA, 13, Font.BOLD, INK));
            n.setSpacingBefore(2f);
            doc.add(n);
            if (metaLine != null && !metaLine.isBlank()) {
                doc.add(new Paragraph(metaLine, F_META));
            }
        } catch (Exception e) {
            throw new IllegalStateException("PDF subjectHeadline failed", e);
        }
    }

    public void spacer(float height) {
        try {
            Paragraph p = new Paragraph(" ");
            p.setLeading(height);
            doc.add(p);
        } catch (Exception e) { /* non-fatal */ }
    }

    public void paragraph(String text, Font font) {
        if (text == null || text.isBlank()) return;
        try { doc.add(new Paragraph(text, font)); }
        catch (Exception e) { throw new IllegalStateException("PDF paragraph failed", e); }
    }

    /** Close the document and return the rendered bytes. */
    public byte[] finish() {
        try {
            doc.close();
        } catch (Exception e) {
            throw new IllegalStateException("Could not finish PDF report", e);
        }
        return out.toByteArray();
    }

    private static Paragraph accentRule(float width, Color color) {
        Paragraph p = new Paragraph("");
        p.setSpacingBefore(3f);
        p.add(new com.lowagie.text.Chunk(new com.lowagie.text.pdf.draw.LineSeparator(
                width, 100f, color, Element.ALIGN_CENTER, -2)));
        p.setSpacingAfter(2f);
        return p;
    }

    /** A FRESH logo Image per call (bytes cached once from the classpath); null-safe. */
    private static Image logo() {
        byte[] bytes = cachedLogoBytes;
        if (bytes == null) {
            try (var in = PdfReport.class.getResourceAsStream("/branding/logo.png")) {
                bytes = in != null ? in.readAllBytes() : EMPTY;
            } catch (Exception e) {
                bytes = EMPTY;
            }
            cachedLogoBytes = bytes;
        }
        if (bytes.length == 0) return null; // brand text still renders; logo is a nice-to-have
        try {
            return Image.getInstance(bytes); // fresh instance — safe across concurrent renders
        } catch (Exception e) {
            return null;
        }
    }

    // ── Every-page chrome: running header (p≥2) + footer w/ attribution + Page X of Y ──
    private static final class Chrome extends PdfPageEventHelper {
        private final Spec spec;
        private final Font footFont = new Font(Font.HELVETICA, 7, Font.NORMAL, MUTED);
        private final Font footStrong = new Font(Font.HELVETICA, 7, Font.BOLD, BRAND_DEEP);
        private final Font runHdr = new Font(Font.HELVETICA, 7.5f, Font.BOLD, MUTED);
        private final Instant generatedAt;
        private PdfTemplate totalPages;

        Chrome(Spec spec, Instant generatedAt) { this.spec = spec; this.generatedAt = generatedAt; }

        @Override
        public void onOpenDocument(PdfWriter writer, Document doc) {
            totalPages = writer.getDirectContent().createTemplate(30, 12);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document doc) {
            PdfContentByte cb = writer.getDirectContent();
            int page = writer.getPageNumber();

            // Running header on continuation pages so a multi-page report stays branded.
            if (page > 1) {
                Phrase h = new Phrase("SmartTriage  ·  " + spec.reportKind(), runHdr);
                ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT, h, doc.right(), doc.top() + 18, 0);
                cb.setColorStroke(HAIRLINE);
                cb.setLineWidth(0.5f);
                cb.moveTo(doc.left(), doc.top() + 14);
                cb.lineTo(doc.right(), doc.top() + 14);
                cb.stroke();
            }

            // Footer hairline.
            float y = doc.bottom() - 16;
            cb.setColorStroke(HAIRLINE);
            cb.setLineWidth(0.5f);
            cb.moveTo(doc.left(), y + 8);
            cb.lineTo(doc.right(), y + 8);
            cb.stroke();

            // Left: confidentiality. Center: attribution. Right: Page X of Y.
            String conf = spec.confidentiality() != null ? spec.confidentiality() : "Confidential";
            ColumnText.showTextAligned(cb, Element.ALIGN_LEFT,
                    new Phrase("CONFIDENTIAL — " + conf, footFont), doc.left(), y, 0);

            String who = (spec.exportedByName() != null && !spec.exportedByName().isBlank())
                    ? spec.exportedByName() : "SmartTriage user";
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                    new Phrase("Generated by " + who + " · " + TS.format(generatedAt), footFont),
                    (doc.left() + doc.right()) / 2, y, 0);

            Phrase pageLabel = new Phrase("Page " + page + " of ", footStrong);
            float len = footStrong.getCalculatedBaseFont(true)
                    .getWidthPoint("Page " + page + " of ", 7f);
            float rightX = doc.right();
            ColumnText.showTextAligned(cb, Element.ALIGN_LEFT, pageLabel, rightX - len - 14, y, 0);
            cb.addTemplate(totalPages, rightX - 14, y);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document doc) {
            totalPages.beginText();
            try {
                totalPages.setFontAndSize(footStrong.getCalculatedBaseFont(true), 7f);
                totalPages.setColorFill(BRAND_DEEP);
                totalPages.showText(String.valueOf(writer.getPageNumber()));
            } catch (Exception ignored) {
                // total-count is cosmetic; never fail the render over it
            } finally {
                totalPages.endText();
            }
        }
    }
}
