package com.smartTriage.smartTriage_server.module.sepsis.service;

import com.smartTriage.smartTriage_server.common.enums.AlertSeverity;
import com.smartTriage.smartTriage_server.common.enums.AlertType;
import com.smartTriage.smartTriage_server.common.enums.SepsisStatus;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.alert.repository.ClinicalAlertRepository;
import com.smartTriage.smartTriage_server.module.sepsis.entity.SepsisScreening;
import com.smartTriage.smartTriage_server.module.sepsis.repository.SepsisScreeningRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.Instant;
import java.util.List;

/**
 * SepsisBundleMonitorService — scheduled monitor for sepsis bundle compliance.
 *
 * Runs every 60 seconds and checks:
 *   1. Bundles in progress that exceed 60 minutes → CRITICAL alert "SEPSIS BUNDLE OVERDUE"
 *   2. Sepsis screenings > 15 minutes old where bundle was never started → CRITICAL alert "SEPSIS BUNDLE NOT STARTED"
 *
 * Bundle compliance is critical: the Surviving Sepsis Campaign mandates completion
 * of the 1-hour bundle to reduce sepsis mortality.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SepsisBundleMonitorService {

    private final SepsisScreeningRepository sepsisScreeningRepository;
    private final ClinicalAlertRepository clinicalAlertRepository;

    private static final long BUNDLE_COMPLETION_DEADLINE_MINUTES = 60;
    private static final long BUNDLE_START_DEADLINE_MINUTES = 15;

    private static final List<SepsisStatus> BUNDLE_REQUIRED_STATUSES = List.of(
            SepsisStatus.SEPSIS_SUSPECTED,
            SepsisStatus.SEVERE_SEPSIS,
            SepsisStatus.SEPTIC_SHOCK
    );

    /**
     * Scheduled task: check bundle compliance every 60 seconds.
     */
    @Scheduled(fixedDelayString = "${smarttriage.sepsis.bundle-check-interval-ms:60000}")
    @Transactional
    public void checkBundleCompliance() {
        int alertsGenerated = 0;

        // Check 1: Bundles in progress that exceed 60 minutes
        alertsGenerated += checkOverdueBundles();

        // Check 2: Sepsis cases where bundle was never started within 15 minutes
        alertsGenerated += checkUnstartedBundles();

        if (alertsGenerated > 0) {
            log.info("Sepsis bundle monitor: generated {} compliance alerts", alertsGenerated);
        }
    }

    /**
     * Check for bundles that have been in progress for more than 60 minutes.
     */
    private int checkOverdueBundles() {
        List<SepsisScreening> bundlesInProgress = sepsisScreeningRepository.findActiveBundlesInProgress();
        int alertCount = 0;

        for (SepsisScreening screening : bundlesInProgress) {
            long minutesSinceStart = Duration.between(screening.getBundleStartedAt(), Instant.now()).toMinutes();

            if (minutesSinceStart > BUNDLE_COMPLETION_DEADLINE_MINUTES) {
                // Check for existing alert to avoid duplicates
                if (!clinicalAlertRepository.existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                        screening.getVisit().getId(), AlertType.SEPSIS_SCREENING)) {

                    String patientName = screening.getVisit().getPatient().getFirstName() + " "
                            + screening.getVisit().getPatient().getLastName();

                    ClinicalAlert alert = ClinicalAlert.builder()
                            .visit(screening.getVisit())
                            .alertType(AlertType.SEPSIS_SCREENING)
                            .severity(AlertSeverity.CRITICAL)
                            .title("SEPSIS BUNDLE OVERDUE")
                            .message(String.format(
                                    "CRITICAL: Sepsis bundle for patient %s (Visit: %s) has been in progress " +
                                    "for %d minutes — exceeds the 60-minute completion deadline. " +
                                    "Status: %s. Bundle started at: %s. " +
                                    "IMMEDIATE ACTION REQUIRED: Complete all remaining bundle items.",
                                    patientName,
                                    screening.getVisit().getVisitNumber(),
                                    minutesSinceStart,
                                    screening.getSepsisStatus().name(),
                                    screening.getBundleStartedAt()))
                            .autoGenerated(true)
                            .build();

                    clinicalAlertRepository.save(alert);
                    alertCount++;

                    log.error("SEPSIS BUNDLE OVERDUE: Visit {} | {} minutes since bundle start",
                            screening.getVisit().getVisitNumber(), minutesSinceStart);
                }
            }
        }

        return alertCount;
    }

    /**
     * Check for sepsis cases where the bundle was never started within 15 minutes of detection.
     */
    private int checkUnstartedBundles() {
        List<SepsisScreening> unstartedCases = sepsisScreeningRepository
                .findSepsisWithoutBundle(BUNDLE_REQUIRED_STATUSES);
        int alertCount = 0;

        for (SepsisScreening screening : unstartedCases) {
            long minutesSinceScreening = Duration.between(screening.getScreenedAt(), Instant.now()).toMinutes();

            if (minutesSinceScreening > BUNDLE_START_DEADLINE_MINUTES) {
                // Check for existing alert to avoid duplicates
                if (!clinicalAlertRepository.existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                        screening.getVisit().getId(), AlertType.SEPSIS_SCREENING)) {

                    String patientName = screening.getVisit().getPatient().getFirstName() + " "
                            + screening.getVisit().getPatient().getLastName();

                    ClinicalAlert alert = ClinicalAlert.builder()
                            .visit(screening.getVisit())
                            .alertType(AlertType.SEPSIS_SCREENING)
                            .severity(AlertSeverity.CRITICAL)
                            .title("SEPSIS BUNDLE NOT STARTED")
                            .message(String.format(
                                    "CRITICAL: Sepsis detected for patient %s (Visit: %s) %d minutes ago " +
                                    "but the 1-hour bundle has NOT been started. " +
                                    "Status: %s. Screened at: %s. " +
                                    "IMMEDIATE ACTION REQUIRED: Start sepsis bundle NOW.",
                                    patientName,
                                    screening.getVisit().getVisitNumber(),
                                    minutesSinceScreening,
                                    screening.getSepsisStatus().name(),
                                    screening.getScreenedAt()))
                            .autoGenerated(true)
                            .build();

                    clinicalAlertRepository.save(alert);
                    alertCount++;

                    log.error("SEPSIS BUNDLE NOT STARTED: Visit {} | {} minutes since screening",
                            screening.getVisit().getVisitNumber(), minutesSinceScreening);
                }
            }
        }

        return alertCount;
    }
}
