package com.smartTriage.smartTriage_server.module.alert.mapper;

import com.smartTriage.smartTriage_server.module.alert.dto.ClinicalAlertResponse;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.clinicalsigns.service.ClinicalSignDefinitions;

public final class ClinicalAlertMapper {

    private ClinicalAlertMapper() {
    }

    public static ClinicalAlertResponse toResponse(ClinicalAlert alert) {
        ClinicalAlertResponse.ClinicalAlertResponseBuilder builder = ClinicalAlertResponse.builder()
                .id(alert.getId())
                .alertType(alert.getAlertType())
                .category(alert.getAlertType() != null ? alert.getAlertType().getCategory() : null)
                .timeCritical(alert.getAlertType() != null && alert.getAlertType().isTimeCritical())
                .severity(alert.getSeverity())
                .title(alert.getTitle())
                .message(alert.getMessage())
                .targetZone(alert.getTargetZone())
                .escalationTier(alert.getEscalationTier())
                .escalatedAt(alert.getEscalatedAt())
                .satsTargetMinutes(alert.getSatsTargetMinutes())
                .acknowledged(alert.isAcknowledged())
                .autoGenerated(alert.isAutoGenerated())
                .createdAt(alert.getCreatedAt())
                // Round 4a — Retriage trigger audit. The frontend
                // click-handler relies on these to navigate the nurse
                // straight to a pre-filled triage form.
                .triggeringSignEventId(alert.getTriggeringSignEventId())
                .triggeringSignCode(alert.getTriggeringSignCode())
                .triggeringSignLabel(
                        alert.getTriggeringSignCode() == null
                                ? null
                                : ClinicalSignDefinitions.labelOrCode(alert.getTriggeringSignCode()));

        // Visit info
        if (alert.getVisit() != null) {
            builder.visitId(alert.getVisit().getId());
            builder.visitNumber(alert.getVisit().getVisitNumber());
            if (alert.getVisit().getPatient() != null) {
                builder.patientName(
                        alert.getVisit().getPatient().getFirstName() + " " +
                                alert.getVisit().getPatient().getLastName());
            }
        }

        // Target doctor
        if (alert.getTargetDoctor() != null) {
            builder.targetDoctorId(alert.getTargetDoctor().getId());
            builder.targetDoctorName(
                    alert.getTargetDoctor().getFirstName() + " " +
                            alert.getTargetDoctor().getLastName());
        }

        // Acknowledged by
        if (alert.getAcknowledgedBy() != null) {
            builder.acknowledgedById(alert.getAcknowledgedBy().getId());
            builder.acknowledgedByName(
                    alert.getAcknowledgedBy().getFirstName() + " " +
                            alert.getAcknowledgedBy().getLastName());
            builder.acknowledgedAt(alert.getAcknowledgedAt());
        }

        return builder.build();
    }
}
