package com.smartTriage.smartTriage_server.module.alert.mapper;

import com.smartTriage.smartTriage_server.module.alert.dto.ClinicalAlertResponse;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.clinicalsigns.service.ClinicalSignDefinitions;

public final class ClinicalAlertMapper {

    private ClinicalAlertMapper() {
    }

    public static ClinicalAlertResponse toResponse(ClinicalAlert alert) {
        ClinicalAlertResponse.ClinicalAlertResponseBuilder builder = ClinicalAlertResponse.builder()
                .id(alert.getId())
                .alertType(alert.getAlertType())
                .category(alert.getAlertType() != null ? alert.getAlertType().getCategory() : null)
                .timeCritical(alert.getAlertType() != null && alert.getAlertType().isTimeCritical())
                .severity(alert.getSeverity())
                .title(alert.getTitle())
                .message(alert.getMessage())
                .targetZone(alert.getTargetZone())
                .escalationTier(alert.getEscalationTier())
                .escalatedAt(alert.getEscalatedAt())
                .satsTargetMinutes(alert.getSatsTargetMinutes())
                .acknowledged(alert.isAcknowledged())
                .autoGenerated(alert.isAutoGenerated())
                .createdAt(alert.getCreatedAt())
                // Round 4a — Retriage trigger audit. The frontend
                // click-handler relies on these to navigate the nurse
                // straight to a pre-filled triage form.
                .triggeringSignEventId(alert.getTriggeringSignEventId())
                .triggeringSignCode(alert.getTriggeringSignCode())
                .triggeringSignLabel(
                        alert.getTriggeringSignCode() == null
                                ? null
                                : ClinicalSignDefinitions.labelOrCode(alert.getTriggeringSignCode()));

        // Visit info — denormalise WHO (patient name) and WHERE (current
        // care zone + bed) onto the alert row so the Alert Center can show
        // who+where without a second fetch. currentZone is the patient's
        // actual location (distinct from targetZone, a routing hint);
        // currentBed is nullable. NULL-SAFE throughout.
        if (alert.getVisit() != null) {
            builder.visitId(alert.getVisit().getId());
            builder.visitNumber(alert.getVisit().getVisitNumber());
            builder.currentZone(alert.getVisit().getCurrentEdZone());
            if (alert.getVisit().getCurrentBed() != null) {
                builder.currentBedLabel(alert.getVisit().getCurrentBed().getCode());
            }
            if (alert.getVisit().getPatient() != null) {
                // Never let a patient-scoped alert render a blank name — a
                // missing identity must read as "Unidentified patient", not
                // an empty row a clinician can't act on.
                String name = ((safe(alert.getVisit().getPatient().getFirstName()) + " "
                        + safe(alert.getVisit().getPatient().getLastName())).trim());
                builder.patientName(name.isEmpty() ? "Unidentified patient" : name);
            }
        }

        // Target doctor
        if (alert.getTargetDoctor() != null) {
            builder.targetDoctorId(alert.getTargetDoctor().getId());
            builder.targetDoctorName(
                    alert.getTargetDoctor().getFirstName() + " " +
                            alert.getTargetDoctor().getLastName());
        }

        // Acknowledged by
        if (alert.getAcknowledgedBy() != null) {
            builder.acknowledgedById(alert.getAcknowledgedBy().getId());
            builder.acknowledgedByName(
                    alert.getAcknowledgedBy().getFirstName() + " " +
                            alert.getAcknowledgedBy().getLastName());
            builder.acknowledgedAt(alert.getAcknowledgedAt());
        }

        return builder.build();
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }
}
