package com.smartTriage.smartTriage_server.module.ems.service;

import com.smartTriage.smartTriage_server.common.enums.AlertSeverity;
import com.smartTriage.smartTriage_server.common.enums.AlertType;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.alert.repository.ClinicalAlertRepository;
import com.smartTriage.smartTriage_server.module.triage.repository.TriageRecordRepository;
import com.smartTriage.smartTriage_server.module.visit.entity.Visit;
import com.smartTriage.smartTriage_server.module.visit.repository.VisitRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;

/**
 * EmsRetriageMonitor — fires
 * {@link AlertType#FIELD_TRIAGED_AWAITING_REVIEW} alerts when an
 * ED has not re-triaged a paramedic-brought patient within the
 * 15-min window.
 *
 * Closes the silent-failure path: a paramedic could call RED, the
 * patient arrives, and 30 min later still no ED triage form has been
 * filled. This scheduler raises the flag at the 15-min mark so the
 * charge nurse intervenes.
 *
 * Self-acks: once the ED nurse files a TriageRecord, the scheduler
 * does not re-fire (existence of a triage record is what clears the
 * deadline).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class EmsRetriageMonitor {

    private final VisitRepository visitRepository;
    private final TriageRecordRepository triageRecordRepository;
    private final ClinicalAlertRepository clinicalAlertRepository;

    @Scheduled(fixedRate = 60_000)
    @Transactional
    public void check() {
        Instant now = Instant.now();
        List<Visit> due = visitRepository.findRetriageDueBefore(now);
        for (Visit v : due) {
            try {
                boolean alreadyTriaged = triageRecordRepository
                        .findFirstByVisitIdAndIsActiveTrueOrderByTriageTimeDesc(v.getId())
                        .isPresent();
                if (alreadyTriaged) {
                    // Clear the deadline so we never re-scan this row.
                    v.setEdRetriageDueAt(null);
                    visitRepository.save(v);
                    continue;
                }

                boolean alertExists = clinicalAlertRepository
                        .existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                                v.getId(), AlertType.FIELD_TRIAGED_AWAITING_REVIEW);
                if (!alertExists) {
                    long minutesOver = java.time.Duration.between(
                            v.getEdRetriageDueAt(), now).toMinutes();
                    ClinicalAlert alert = ClinicalAlert.builder()
                            .visit(v)
                            .alertType(AlertType.FIELD_TRIAGED_AWAITING_REVIEW)
                            .severity(AlertSeverity.HIGH)
                            .title("Re-triage overdue: " + safeTriageLabel(v))
                            .message(String.format(
                                    "Paramedic-brought patient (visit %s, field triage %s) has not been re-triaged " +
                                            "by the ED — overdue by %d min. Confirm the field call still holds.",
                                    v.getVisitNumber(),
                                    v.getFieldTriageCategory() != null ? v.getFieldTriageCategory() : "?",
                                    minutesOver))
                            .autoGenerated(true)
                            .build();
                    clinicalAlertRepository.save(alert);
                    log.warn("[ems] FIELD_TRIAGED_AWAITING_REVIEW raised for visit {} ({} min overdue)",
                            v.getVisitNumber(), minutesOver);
                }
            } catch (Exception e) {
                log.error("[ems] retriage monitor error for visit {}: {}", v.getId(), e.getMessage());
            }
        }
    }

    private static String safeTriageLabel(Visit v) {
        return v.getFieldTriageCategory() != null
                ? "field " + v.getFieldTriageCategory()
                : "EMS arrival";
    }
}
