package com.smartTriage.smartTriage_server.module.alert.dto;

import com.smartTriage.smartTriage_server.common.enums.AlertSeverity;
import com.smartTriage.smartTriage_server.common.enums.AlertType;
import com.smartTriage.smartTriage_server.common.enums.EdZone;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * Alert response DTO — includes zone-aware escalation fields.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ClinicalAlertResponse {

    private UUID id;
    private UUID visitId;
    private String visitNumber;
    private String patientName;
    private AlertType alertType;
    private AlertSeverity severity;
    private String title;
    private String message;

    // Zone-aware escalation
    private EdZone targetZone;
    private int escalationTier;
    private Instant escalatedAt;
    private UUID targetDoctorId;
    private String targetDoctorName;
    private Integer satsTargetMinutes;

    // Acknowledgment
    private boolean acknowledged;
    private UUID acknowledgedById;
    private String acknowledgedByName;
    private Instant acknowledgedAt;

    private boolean autoGenerated;
    private Instant createdAt;

    // Round 4a — RETRIAGE_REQUIRED trigger audit. Null for every other
    // alert type. The label resolves server-side from
    // ClinicalSignDefinitions so the frontend doesn't need its own
    // catalog lookup at click time.
    private UUID triggeringSignEventId;
    private String triggeringSignCode;
    private String triggeringSignLabel;
}
