package com.smartTriage.smartTriage_server.module.alert.service;

import com.smartTriage.smartTriage_server.common.enums.*;
import com.smartTriage.smartTriage_server.module.alert.dto.ClinicalAlertResponse;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.alert.mapper.ClinicalAlertMapper;
import com.smartTriage.smartTriage_server.module.alert.repository.ClinicalAlertRepository;
import com.smartTriage.smartTriage_server.module.iot.service.RealTimeEventPublisher;
import com.smartTriage.smartTriage_server.module.shift.service.ShiftAssignmentService;
import com.smartTriage.smartTriage_server.module.user.entity.User;
import com.smartTriage.smartTriage_server.module.visit.entity.Visit;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Alert Escalation Service — implements the SmartTriage tiered notification
 * system.
 *
 * When a patient is triaged RED or ORANGE:
 * Tier 1 (instant): Route to zone doctor + charge nurse — "Dr. X, new ORANGE in
 * ACUTE bay 3"
 * Tier 2 (+2 min unacknowledged): Broadcast to ALL on-duty doctors —
 * "Unacknowledged ORANGE"
 * Tier 3 (+5 min unacknowledged): Alert EVERYONE on shift + flag audible alarm
 *
 * SATS target times:
 * RED → 0 min (immediate)
 * ORANGE → 10 min (doctor MUST see within 10 min)
 * YELLOW → 30 min
 * GREEN → 60 min
 *
 * The escalation scheduler runs every 30 seconds checking for unacknowledged
 * alerts.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AlertEscalationService {

    private final ClinicalAlertRepository clinicalAlertRepository;
    private final ShiftAssignmentService shiftAssignmentService;
    private final RealTimeEventPublisher eventPublisher;

    // Escalation thresholds
    private static final int TIER_2_MINUTES = 2;
    private static final int TIER_3_MINUTES = 5;

    /**
     * Create and route a doctor notification alert for a triaged patient.
     * Called by TriageService when a patient is triaged RED/ORANGE.
     */
    @Transactional
    public ClinicalAlert createZoneRoutedAlert(Visit visit, TriageCategory category, int tewsScore,
            String decisionPath) {
        UUID hospitalId = visit.getPatient().getHospital().getId();
        EdZone targetZone = EdZone.fromTriageCategory(category);

        // Determine SATS target minutes
        int satsMinutes = getSatsTargetMinutes(category);

        // Find zone doctor(s)
        List<User> zoneDoctors = shiftAssignmentService.getDoctorsForZone(hospitalId, targetZone);
        User targetDoctor = zoneDoctors.isEmpty() ? null : zoneDoctors.get(0);

        AlertSeverity severity = category == TriageCategory.RED ? AlertSeverity.CRITICAL : AlertSeverity.HIGH;
        AlertType alertType = AlertType.DOCTOR_NOTIFICATION;

        String patientName = visit.getPatient().getFirstName() + " " + visit.getPatient().getLastName();
        String doctorLabel = targetDoctor != null
                ? "Dr. " + targetDoctor.getLastName()
                : "No doctor assigned to " + targetZone.name();

        ClinicalAlert alert = ClinicalAlert.builder()
                .visit(visit)
                .alertType(alertType)
                .severity(severity)
                .title(String.format("%s Triage — %s", category.name(), visit.getVisitNumber()))
                .message(String.format(
                        "%s, new %s patient %s in %s zone (TEWS: %d). %s. SATS target: %d min.",
                        doctorLabel, category.name(), patientName, targetZone.name(),
                        tewsScore, decisionPath, satsMinutes))
                .targetZone(targetZone)
                .escalationTier(1)
                .escalatedAt(Instant.now())
                .targetDoctor(targetDoctor)
                .satsTargetMinutes(satsMinutes)
                .autoGenerated(true)
                .build();

        alert = clinicalAlertRepository.save(alert);
        log.info("TIER 1 ALERT: {} patient {} → {} zone → {} | Alert ID: {}",
                category, patientName, targetZone, doctorLabel, alert.getId());

        // Push WebSocket notification
        ClinicalAlertResponse response = ClinicalAlertMapper.toResponse(alert);

        // Send to zone topic (zone doctor + nurses in that zone)
        eventPublisher.publishZoneAlert(hospitalId, targetZone, response);

        // Also send to hospital-wide alert topic (all dashboards)
        eventPublisher.publishHospitalAlert(hospitalId, response);

        // Notify the target zone doctor directly via user-targeted topic
        if (targetDoctor != null) {
            eventPublisher.publishUserAlert(targetDoctor.getId(), response);
        }

        // Notify the charge nurse on duty via user-targeted topic (Tier 1 recipient)
        List<User> chargeNurses = shiftAssignmentService.getChargeNurse(hospitalId);
        for (User cn : chargeNurses) {
            eventPublisher.publishUserAlert(cn.getId(), response);
        }

        // If zone has no doctor assigned, immediately escalate to Tier 2
        if (targetDoctor == null) {
            log.warn("No doctor assigned to {} zone — auto-escalating to Tier 2", targetZone);
            escalateToTier2(alert, hospitalId);
        }

        return alert;
    }

    /**
     * Scheduled escalation check — runs every 30 seconds.
     * Finds unacknowledged alerts and escalates them through tiers.
     */
    @Scheduled(fixedRate = 30_000)
    @Transactional
    public void checkEscalations() {
        // Find all unacknowledged DOCTOR_NOTIFICATION alerts
        List<ClinicalAlert> unacknowledged = clinicalAlertRepository
                .findUnacknowledgedDoctorNotifications();

        for (ClinicalAlert alert : unacknowledged) {
            if (alert.getEscalatedAt() == null)
                continue;

            long minutesSinceEscalation = ChronoUnit.MINUTES.between(alert.getEscalatedAt(), Instant.now());
            UUID hospitalId = alert.getVisit().getPatient().getHospital().getId();

            if (alert.getEscalationTier() == 1 && minutesSinceEscalation >= TIER_2_MINUTES) {
                escalateToTier2(alert, hospitalId);
            } else if (alert.getEscalationTier() == 2 && minutesSinceEscalation >= TIER_3_MINUTES) {
                escalateToTier3(alert, hospitalId);
            }
        }

        // Time-critical clinical alerts (sepsis, ICU escalation, critical
        // lab unack, deterioration) — separate pipeline because they don't
        // share DOCTOR_NOTIFICATION's tier semantics, but they share the
        // need for "if nobody ack'd this, re-broadcast to everyone".
        // Single bump: if the alert has been unack'd for >= TIER_3_MINUTES
        // (the most-aggressive threshold the existing pipeline uses), we
        // re-publish hospital-wide with the audible-alarm flag so the
        // CriticalAlertNotifier on every connected client beeps + flashes
        // again. Idempotent — we only re-publish once per alert by
        // tracking escalatedAt the same way the doctor pipeline does.
        for (ClinicalAlert alert : clinicalAlertRepository.findUnacknowledgedTimeCriticalAlerts()) {
            try {
                if (alert.getEscalatedAt() != null) {
                    continue; // already re-paged once
                }
                long minutesSinceCreate = ChronoUnit.MINUTES
                        .between(alert.getCreatedAt() != null ? alert.getCreatedAt() : Instant.now(), Instant.now());
                if (minutesSinceCreate < TIER_3_MINUTES) {
                    continue; // still inside the ack window
                }
                UUID hospitalId = alert.getVisit().getPatient().getHospital().getId();
                rebroadcastTimeCriticalAlert(alert, hospitalId);
            } catch (Exception e) {
                log.warn("Failed to escalate time-critical alert {}: {}",
                        alert.getId(), e.getMessage());
            }
        }
    }

    /**
     * Mark a time-critical alert as escalated and re-publish it
     * hospital-wide with audible-alarm + escalationTier=2 so connected
     * clients beep + flash again. Tier 3 isn't applicable here — these
     * alert types don't have the manual ack-by-doctor flow that
     * DOCTOR_NOTIFICATION does; the second broadcast IS the escalation.
     */
    private void rebroadcastTimeCriticalAlert(ClinicalAlert alert, UUID hospitalId) {
        alert.setEscalatedAt(Instant.now());
        alert.setEscalationTier(2);
        alert.setSeverity(AlertSeverity.CRITICAL);
        alert.setMessage(alert.getMessage() + "  [ESCALATED — unacknowledged for "
                + TIER_3_MINUTES + " minutes]");
        clinicalAlertRepository.save(alert);

        java.util.Map<String, Object> alertWithAlarm = new java.util.HashMap<>();
        alertWithAlarm.put("alert", com.smartTriage.smartTriage_server.module.alert.mapper
                .ClinicalAlertMapper.toResponse(alert));
        alertWithAlarm.put("audibleAlarm", true);
        eventPublisher.publishAlert(hospitalId, alertWithAlarm);

        log.warn("[escalation] {} alert {} escalated — unacked for {}+ min, hospital {}",
                alert.getAlertType(), alert.getId(), TIER_3_MINUTES, hospitalId);
    }

    /**
     * Tier 2 escalation — broadcast to ALL on-duty doctors.
     */
    private void escalateToTier2(ClinicalAlert alert, UUID hospitalId) {
        alert.setEscalationTier(2);
        alert.setEscalatedAt(Instant.now());
        alert.setAlertType(AlertType.DOCTOR_ESCALATION);
        alert.setSeverity(AlertSeverity.CRITICAL);
        alert = clinicalAlertRepository.save(alert);

        String patientName = alert.getVisit().getPatient().getFirstName() + " "
                + alert.getVisit().getPatient().getLastName();
        log.warn("TIER 2 ESCALATION: Alert {} for patient {} — broadcasting to ALL doctors",
                alert.getId(), patientName);

        ClinicalAlertResponse response = ClinicalAlertMapper.toResponse(alert);

        // Send to all on-duty doctors via user-targeted topics
        List<User> allDoctors = shiftAssignmentService.getAllDoctorsOnDuty(hospitalId);
        for (User doctor : allDoctors) {
            eventPublisher.publishUserAlert(doctor.getId(), response);
        }

        // Update hospital-wide alert
        eventPublisher.publishHospitalAlert(hospitalId, response);
    }

    /**
     * Tier 3 escalation — alert EVERYONE on shift + audible alarm flag.
     */
    private void escalateToTier3(ClinicalAlert alert, UUID hospitalId) {
        alert.setEscalationTier(3);
        alert.setEscalatedAt(Instant.now());
        alert.setSeverity(AlertSeverity.CRITICAL);
        alert = clinicalAlertRepository.save(alert);

        String patientName = alert.getVisit().getPatient().getFirstName() + " "
                + alert.getVisit().getPatient().getLastName();
        log.error("TIER 3 ESCALATION: Alert {} for patient {} — alerting ALL STAFF + AUDIBLE ALARM",
                alert.getId(), patientName);

        ClinicalAlertResponse response = ClinicalAlertMapper.toResponse(alert);

        // Broadcast to all zones
        for (EdZone zone : EdZone.values()) {
            eventPublisher.publishZoneAlert(hospitalId, zone, response);
        }

        // Send hospital-wide ClinicalAlertResponse
        eventPublisher.publishHospitalAlert(hospitalId, response);

        // Also send hospital-wide with audible alarm flag for dashboards that support
        // it
        Map<String, Object> data = alertToMap(response);
        data.put("audibleAlarm", true);
        data.put("escalationMessage", "CRITICAL: Patient " + patientName
                + " has been waiting " + alert.getSatsTargetMinutes()
                + "+ minutes without doctor acknowledgment!");
        eventPublisher.publishAlert(hospitalId, data);
    }

    /**
     * Get SATS maximum wait time in minutes for a triage category.
     */
    public static int getSatsTargetMinutes(TriageCategory category) {
        return switch (category) {
            case RED -> 0;
            case ORANGE -> 10;
            case YELLOW -> 30;
            case GREEN -> 60;
            case BLUE -> 120;
        };
    }

    /**
     * Convert ClinicalAlertResponse to a Map for WebSocket publishing.
     */
    private Map<String, Object> alertToMap(ClinicalAlertResponse r) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("id", r.getId().toString());
        map.put("type", r.getAlertType().name());
        map.put("severity", r.getSeverity().name());
        map.put("title", r.getTitle());
        map.put("message", r.getMessage());
        map.put("escalationTier", r.getEscalationTier());
        map.put("satsTargetMinutes", r.getSatsTargetMinutes());
        map.put("acknowledged", r.isAcknowledged());
        map.put("createdAt", r.getCreatedAt() != null ? r.getCreatedAt().toString() : null);

        if (r.getVisitId() != null)
            map.put("visitId", r.getVisitId().toString());
        if (r.getVisitNumber() != null)
            map.put("visitNumber", r.getVisitNumber());
        if (r.getPatientName() != null)
            map.put("patientName", r.getPatientName());
        if (r.getTargetZone() != null)
            map.put("targetZone", r.getTargetZone().name());
        if (r.getTargetDoctorId() != null)
            map.put("targetDoctorId", r.getTargetDoctorId().toString());
        if (r.getTargetDoctorName() != null)
            map.put("targetDoctorName", r.getTargetDoctorName());

        return map;
    }
}
