package com.smartTriage.smartTriage_server.module.zonetransfer.entity;

import com.smartTriage.smartTriage_server.common.entity.BaseEntity;
import com.smartTriage.smartTriage_server.common.enums.EdZone;
import com.smartTriage.smartTriage_server.module.user.entity.User;
import com.smartTriage.smartTriage_server.module.visit.entity.Visit;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * ZoneTransfer — captures a pending or completed inter-zone move
 * within an ED visit.
 *
 * <p>Created when a patient's category changes such that the implied
 * zone differs from where they physically are (auto re-triage,
 * manual re-triage, charge-nurse-initiated reassignment). Lives in
 * {@link ZoneTransferStatus#PENDING_ACCEPT} until a receiving doctor
 * explicitly accepts (moves the patient + transfers responsibility),
 * declines (patient stays in original zone), or the team converts
 * it to {@link ZoneTransferStatus#RESUS_IN_PLACE} (treat at higher
 * acuity without physically moving).
 *
 * <p>The state machine is the safety boundary: until a receiving
 * doctor takes the patient, the ORIGINAL doctor remains responsible.
 * No orphan windows.
 *
 * <p>FK columns referencing the trigger event/alert give us the audit
 * chain: clinical-sign event → alert → triage record → zone transfer.
 * Each step traceable to a clinician + timestamp.
 */
@Entity
@Table(name = "zone_transfers")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ZoneTransfer extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visit_id", nullable = false)
    private Visit visit;

    /**
     * The zone the patient was in when the transfer was initiated.
     * Null when the patient hadn't been placed in a zone yet (rare —
     * post-registration, pre-triage transition).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "from_zone", length = 20)
    private EdZone fromZone;

    @Enumerated(EnumType.STRING)
    @Column(name = "to_zone", nullable = false, length = 20)
    private EdZone toZone;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private ZoneTransferStatus status;

    /**
     * Clinical reason for the transfer — typically a templated string
     * generated by the system ("Auto re-triage: Hypoglycaemia → RED")
     * or a free-text note from a manual initiator.
     */
    @Column(name = "reason", columnDefinition = "TEXT")
    private String reason;

    @Column(name = "initiated_at", nullable = false)
    private Instant initiatedAt;

    /**
     * The user who initiated the transfer. Null for system-initiated
     * transfers (auto re-triage from a worsening clinical sign).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "initiated_by_id")
    private User initiatedBy;

    /**
     * The receiving zone's on-shift doctor at the time of initiation,
     * if any. Null when no doctor is currently assigned to the
     * receiving zone (gap in roster) — escalates to charge nurse
     * immediately.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proposed_clinician_id")
    private User proposedClinician;

    @Column(name = "accepted_at")
    private Instant acceptedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "accepted_by_id")
    private User acceptedBy;

    @Column(name = "declined_at")
    private Instant declinedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "declined_by_id")
    private User declinedBy;

    @Column(name = "declined_reason", columnDefinition = "TEXT")
    private String declinedReason;

    /**
     * SBAR-shaped handover note set at acceptance time. Required at
     * ACCEPTED transitions for safety; can be free-form for
     * RESUS_IN_PLACE / DECLINED.
     */
    @Column(name = "handover_note", columnDefinition = "TEXT")
    private String handoverNote;

    /**
     * The clinical_alerts row that drove this transfer (optional).
     * Populated for system-triggered transfers from auto re-triage so
     * acknowledging the alert and accepting the transfer can be tied
     * together in the audit trail.
     */
    @Column(name = "triggering_alert_id")
    private UUID triggeringAlertId;

    /**
     * The clinical_sign_events row that produced the auto re-triage
     * (optional). Same audit-chain rationale as triggering_alert_id.
     */
    @Column(name = "triggering_sign_event_id")
    private UUID triggeringSignEventId;
}
