/* ── API barrel export ── */
export { apiRequest, get, post, put, patch, del, ApiError, getAccessToken, setTokens, clearTokens, restoreTokens } from './client';
export { authApi } from './auth';
export { patientApi } from './patients';
export { patientAllergyApi } from './patientAllergies';
export { patientChronicConditionApi } from './patientChronicConditions';
export { visitApi } from './visits';
export { vitalApi } from './vitals';
export { triageApi } from './triage';
export { clinicalNoteApi } from './clinicalNotes';
export { diagnosisApi } from './diagnoses';
export { investigationApi } from './investigations';
export { medicationApi } from './medications';
export { iotApi } from './iot';
export { bedsApi } from './beds';
export { alertApi } from './alerts';
export { hospitalApi } from './hospitals';
export { userApi } from './users';
export { shiftApi } from './shifts';
export { shiftTemplateApi } from './shiftTemplates';
export { delegationApi } from './delegations';
export { leaveApi } from './leaves';
export { swapApi } from './swaps';
export { sepsisApi } from './sepsis';
export { fasttrackApi } from './fasttrack';
export { hypoglycemiaApi } from './hypoglycemia';
export { isolationApi } from './isolation';
export { documentationApi } from './documentation';
export { medsafetyApi } from './medsafety';
export { labApi } from './lab';
export { pathwayApi } from './pathway';
export { icuApi } from './icu';
export { safetyApi } from './safety';
export { handoverApi } from './handover';
export { qualityApi } from './quality';
export { predictionApi } from './prediction';
export { mohReportApi } from './mohreport';
export { governanceApi } from './governance';
export { connectWebSocket, disconnectWebSocket, subscribeToVitals, subscribeToAlerts, subscribeToZoneAlerts, subscribeToUserAlerts, subscribeToDevices, subscribeToTriageChanges, subscribeToBedChanges, subscribeToLabOrders, subscribeToMedications } from './websocket';
export type { BedChangeEvent } from './websocket';
export type * from './types';
