package com.smartTriage.smartTriage_server.module.handover.service;

import com.smartTriage.smartTriage_server.module.handover.dto.GenerateShiftHandoverRequest;
import com.smartTriage.smartTriage_server.module.hospital.entity.Hospital;
import com.smartTriage.smartTriage_server.module.hospital.repository.HospitalRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Auto-generates per-visit handover reports 15 minutes before each shift
 * boundary so the incoming team always has a fresh briefing waiting when
 * they log in.
 *
 * <h2>Why automatic, not manual</h2>
 * The legacy flow required a Charge Nurse to click "Generate" before any
 * handover report existed for an active visit. In a busy ED that step
 * gets skipped, and the incoming night doctor at 19:00 arrives to a
 * cold queue: full chart history is there, but no synthesis of "what
 * matters right now". The scheduler closes that gap — handover reports
 * are a guarantee, not a hope.
 *
 * <h2>Cadence</h2>
 * Two cron triggers, both Africa/Kigali (the deployment timezone):
 * <ul>
 *   <li>{@code 06:30} — fires before the day shift starts at 07:00.
 *       Captures the night shift's clinical state.</li>
 *   <li>{@code 18:30} — fires before the night shift starts at 19:00.
 *       Captures the day shift's clinical state.</li>
 * </ul>
 * 30-minute lead time matches the {@code SHIFT_LEAD_GRACE} window so
 * reports are ready when the incoming staff arrive without overlapping
 * the previous shift's still-active workflow.
 *
 * <h2>Idempotency</h2>
 * The underlying {@link HandoverReportService#generateBulkShiftHandover}
 * already creates one report per active visit; re-running before the
 * next shift boundary stacks newer reports on top of older ones rather
 * than mutating in place — that's the right model because each shift
 * change is a new clinical state, not a mutation of an old one. If the
 * scheduler restart-fires within the same boundary, you get duplicate
 * reports for that boundary; we accept that over the alternative
 * (suppressing a real shift-change report because a transient process
 * fired the cron twice).
 *
 * <h2>Failure isolation</h2>
 * The bulk method swallows per-visit exceptions internally so one
 * problem visit cannot block reports for the rest. We add hospital-level
 * isolation here so one problem hospital cannot block reports for the
 * rest of the multi-tenant fleet.
 *
 * @see ShiftMaterializerScheduler — the adjacent scheduler that
 *      materialises rosters at 06:45 / 18:45 (15 minutes after the
 *      handover reports are ready).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class HandoverReportScheduler {

    private final HandoverReportService handoverReportService;
    private final HospitalRepository hospitalRepository;

    /** Fires 30 minutes before the day shift (07:00 Africa/Kigali). */
    @Scheduled(cron = "0 30 6 * * *", zone = "Africa/Kigali")
    public void generateNightToDayHandover() {
        runForAllHospitals("NIGHT→DAY (06:30)");
    }

    /** Fires 30 minutes before the night shift (19:00 Africa/Kigali). */
    @Scheduled(cron = "0 30 18 * * *", zone = "Africa/Kigali")
    public void generateDayToNightHandover() {
        runForAllHospitals("DAY→NIGHT (18:30)");
    }

    private void runForAllHospitals(String boundary) {
        List<Hospital> hospitals = hospitalRepository.findByIsActiveTrue();
        log.info("[handover-scheduler] {} sweep starting — {} active hospitals",
                boundary, hospitals.size());

        int hospitalsReported = 0;
        int hospitalsFailed = 0;
        int totalReports = 0;

        // The "generated by" actor for system-triggered reports. Distinct
        // from a human name so audit logs make the source obvious. The
        // handover viewer already shows this string verbatim.
        GenerateShiftHandoverRequest request = GenerateShiftHandoverRequest.builder()
                .generatedByName("System (auto " + boundary + ")")
                .notes("Auto-generated at shift boundary by HandoverReportScheduler.")
                .build();

        for (Hospital hospital : hospitals) {
            try {
                int n = handoverReportService
                        .generateBulkShiftHandover(hospital.getId(), request)
                        .size();
                totalReports += n;
                hospitalsReported++;
                log.info("[handover-scheduler] {} → {} ({}): {} reports",
                        boundary, hospital.getName(), hospital.getHospitalCode(), n);
            } catch (Exception e) {
                hospitalsFailed++;
                log.error("[handover-scheduler] {} → {} ({}): FAILED — {}",
                        boundary, hospital.getName(), hospital.getHospitalCode(),
                        e.getMessage(), e);
            }
        }

        log.info("[handover-scheduler] {} sweep complete: {} hospitals OK, {} failed, {} reports total",
                boundary, hospitalsReported, hospitalsFailed, totalReports);
    }
}
