package com.smartTriage.smartTriage_server.module.lab.service;

import com.smartTriage.smartTriage_server.common.enums.AlertSeverity;
import com.smartTriage.smartTriage_server.common.enums.AlertType;
import com.smartTriage.smartTriage_server.common.enums.LabPriority;
import com.smartTriage.smartTriage_server.module.alert.entity.ClinicalAlert;
import com.smartTriage.smartTriage_server.module.alert.repository.ClinicalAlertRepository;
import com.smartTriage.smartTriage_server.module.lab.entity.LabOrder;
import com.smartTriage.smartTriage_server.module.lab.repository.LabOrderRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.Instant;
import java.util.List;

/**
 * LabTurnaroundMonitorService — scheduled service that monitors lab order
 * turnaround times and escalates overdue orders.
 *
 * Runs every 60 seconds and checks:
 *   - STAT orders: if > 30 min from orderedAt without result → HIGH alert
 *   - URGENT orders: if > 2 hours from orderedAt without result → HIGH alert
 *   - Critical results not acknowledged within 15 minutes → CRITICAL escalation
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class LabTurnaroundMonitorService {

    private final LabOrderRepository labOrderRepository;
    private final ClinicalAlertRepository clinicalAlertRepository;

    private static final int STAT_OVERDUE_MINUTES = 30;
    private static final int URGENT_OVERDUE_MINUTES = 120;
    private static final int CRITICAL_ACK_TIMEOUT_MINUTES = 15;

    /**
     * Monitor lab turnaround times and generate alerts for overdue orders.
     * Runs every 60 seconds.
     */
    @Scheduled(fixedRate = 60_000)
    @Transactional
    public void monitorTurnaroundTimes() {
        Instant now = Instant.now();

        checkOverdueStatOrders(now);
        checkOverdueUrgentOrders(now);
        checkUnacknowledgedCriticalResults(now);
    }

    /**
     * Check STAT orders — alert if > 30 minutes without result.
     */
    private void checkOverdueStatOrders(Instant now) {
        Instant statCutoff = now.minus(Duration.ofMinutes(STAT_OVERDUE_MINUTES));
        List<LabOrder> overdueStatOrders = labOrderRepository.findOverdueOrdersByPriority(
                LabPriority.STAT, statCutoff);

        for (LabOrder order : overdueStatOrders) {
            long minutesWaiting = Duration.between(order.getOrderedAt(), now).toMinutes();

            // Avoid duplicate alerts — check if one already exists for this order
            boolean alertExists = clinicalAlertRepository
                    .existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                            order.getVisit().getId(), AlertType.STAT_LAB_OVERDUE);

            if (!alertExists) {
                ClinicalAlert alert = ClinicalAlert.builder()
                        .visit(order.getVisit())
                        .alertType(AlertType.STAT_LAB_OVERDUE)
                        .severity(AlertSeverity.HIGH)
                        .title("STAT LAB OVERDUE: " + order.getTestName())
                        .message(String.format("STAT lab order %s (%s) has been waiting %d minutes " +
                                        "(target: %d min). Ordered by %s.",
                                order.getOrderNumber(),
                                order.getTestName(),
                                minutesWaiting,
                                STAT_OVERDUE_MINUTES,
                                order.getOrderedByName() != null ? order.getOrderedByName() : "unknown"))
                        .autoGenerated(true)
                        .build();

                clinicalAlertRepository.save(alert);
                log.warn("STAT LAB OVERDUE alert for order {} — {} min waiting",
                        order.getOrderNumber(), minutesWaiting);
            }
        }
    }

    /**
     * Check URGENT orders — alert if > 2 hours without result.
     */
    private void checkOverdueUrgentOrders(Instant now) {
        Instant urgentCutoff = now.minus(Duration.ofMinutes(URGENT_OVERDUE_MINUTES));
        List<LabOrder> overdueUrgentOrders = labOrderRepository.findOverdueOrdersByPriority(
                LabPriority.URGENT, urgentCutoff);

        for (LabOrder order : overdueUrgentOrders) {
            long minutesWaiting = Duration.between(order.getOrderedAt(), now).toMinutes();

            boolean alertExists = clinicalAlertRepository
                    .existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                            order.getVisit().getId(), AlertType.URGENT_LAB_OVERDUE);

            if (!alertExists) {
                ClinicalAlert alert = ClinicalAlert.builder()
                        .visit(order.getVisit())
                        .alertType(AlertType.URGENT_LAB_OVERDUE)
                        .severity(AlertSeverity.HIGH)
                        .title("URGENT LAB OVERDUE: " + order.getTestName())
                        .message(String.format("URGENT lab order %s (%s) has been waiting %d minutes " +
                                        "(target: %d min). Ordered by %s.",
                                order.getOrderNumber(),
                                order.getTestName(),
                                minutesWaiting,
                                URGENT_OVERDUE_MINUTES,
                                order.getOrderedByName() != null ? order.getOrderedByName() : "unknown"))
                        .autoGenerated(true)
                        .build();

                clinicalAlertRepository.save(alert);
                log.warn("URGENT LAB OVERDUE alert for order {} — {} min waiting",
                        order.getOrderNumber(), minutesWaiting);
            }
        }
    }

    /**
     * Check critical results not acknowledged within 15 minutes — escalate.
     */
    private void checkUnacknowledgedCriticalResults(Instant now) {
        Instant ackCutoff = now.minus(Duration.ofMinutes(CRITICAL_ACK_TIMEOUT_MINUTES));
        List<LabOrder> unacknowledged = labOrderRepository.findUnacknowledgedCriticalResultsBefore(ackCutoff);

        for (LabOrder order : unacknowledged) {
            long minutesSinceResult = Duration.between(order.getResultedAt(), now).toMinutes();

            boolean alertExists = clinicalAlertRepository
                    .existsByVisitIdAndAlertTypeAndIsAcknowledgedFalseAndIsActiveTrue(
                            order.getVisit().getId(), AlertType.CRITICAL_VALUE_UNACKNOWLEDGED);

            if (!alertExists) {
                ClinicalAlert alert = ClinicalAlert.builder()
                        .visit(order.getVisit())
                        .alertType(AlertType.CRITICAL_VALUE_UNACKNOWLEDGED)
                        .severity(AlertSeverity.CRITICAL)
                        .title("CRITICAL VALUE UNACKNOWLEDGED: " + order.getTestName())
                        .message(String.format("CRITICAL lab result for %s (Order %s) has NOT been acknowledged " +
                                        "after %d minutes. Result: %s %s. %s. " +
                                        "IMMEDIATE clinician response required.",
                                order.getTestName(),
                                order.getOrderNumber(),
                                minutesSinceResult,
                                order.getResultValue(),
                                order.getResultUnit() != null ? order.getResultUnit() : "",
                                order.getCriticalValueType() != null ? order.getCriticalValueType().getDescription() : ""))
                        .autoGenerated(true)
                        .build();

                clinicalAlertRepository.save(alert);
                log.warn("CRITICAL VALUE UNACKNOWLEDGED escalation for order {} — {} min since result",
                        order.getOrderNumber(), minutesSinceResult);
            }
        }
    }
}
