package com.smartTriage.smartTriage_server.module.handover.dto;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GenerateShiftHandoverRequest {

    @NotNull(message = "Generated by name is required")
    private String generatedByName;

    private String notes;
}
